pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: Node install
  inputs:
    versionSpec: '10.15.1'

- bash: node --version && yarn --version
  displayName: 'Print versions'

- bash: yarn install
  displayName: 'Install dependencies'

- bash: yarn test
  displayName: 'Run linting and unit tests'

- bash: yarn run build
  displayName: 'Build library'
