pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: Node install
  inputs:
    versionSpec: '10.15.1'

- bash: node --version
  displayName: 'Print versions'

- bash: npm install
  displayName: 'Install dependencies'

- bash: npm test
  displayName: 'Run linting and unit tests'

- bash: npm run build
  displayName: 'Build library'
